version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "github-actions"
    directories:
      # "/" refers to /.github/workflows
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
