name: Scan code

runs:
  using: "composite"
  steps:
    # Sobelow is a security-focused static analysis tool for the Phoenix framework. https://sobelow.io/
    - name: Run Sobelow and generate report
      id: run-action
      uses: sobelow/action@1afd6d2cae70ae8bd900b58506f54487ed863912

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
