name: Test Dockerfile

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: changes
      with:
        filters: |
          Dockerfile:
            - 'Dockerfile'
    - name: Build Dockerfile
      shell: bash
      if: steps.changes.outputs.Dockerfile == 'true'
      run: docker build .
