name: Test Dockerfile

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      id: changes
      with:
        filters: |
          Dockerfile:
            - 'Dockerfile'
    - name: Build Dockerfile
      shell: bash
      if: steps.changes.outputs.Dockerfile == 'true'
      run: docker build .
