name: Test Dockerfile

runs:
  using: "composite"
  steps:
    - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
      id: changes
      with:
        filters: |
          Dockerfile:
            - 'Dockerfile'
    - name: Build Dockerfile
      shell: bash
      if: steps.changes.outputs.Dockerfile == 'true'
      run: docker build .
