name: Test setup
description: Setup the test environment

runs:
  using: "composite"
  steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@3ba5b86a2a6916f8cb0e64dcca30a56732a34bdf
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      shell: bash
      run: mix deps.get --check-locked
