name: Deploy to Fly

inputs:
  fly_api_token:
    description: Fly API token
    required: true

runs:
  using: "composite"
  steps:
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly_api_token }}