name: Code style
description: Check code formatting, lint with Credo, and check gettext files

runs:
  using: "composite"
  steps:
    - name: Check formatting
      shell: bash
      run: mix format --check-formatted

    - name: Run Credo
      shell: bash
      run: mix credo --strict

    - name: Check gettext files are up-to-date
      shell: bash
      run: mix gettext.extract --check-up-to-date
