name: Scan code

runs:
  using: "composite"
  steps:
    # Sobelow is a security-focused static analysis tool for the Phoenix framework. https://sobelow.io/
    - name: Run Sobelow and generate report
      id: run-action
      uses: sobelow/action@4c2cc216597acef2c5f8b4b2e49ad591be36ce36

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
