name: Build Elixir
description: Install dependencies and compile the project

inputs:
  otp-version:
    description: Installed OTP version, from the setup-elixir action
    required: true
  elixir-version:
    description: Installed Elixir version, from the setup-elixir action
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore dependencies & _build cache
      id: build_cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        key: |
          build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}
        path: |
          deps
          _build

    - name: Install dependencies
      if: steps.build_cache.outputs.cache-hit != 'true'
      shell: bash
      run: mix deps.get --check-locked

    - name: Compile dependencies
      if: steps.build_cache.outputs.cache-hit != 'true'
      shell: bash
      run: mix deps.compile

    - name: Save dependencies & _build cache
      id: build_cache_save
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      if: steps.build_cache.outputs.cache-hit != 'true'
      with:
        key: |
          build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
        path: |
          deps
          _build

    - name: Compile project
      shell: bash
      run: mix compile --warnings-as-errors
