name: Deploy to Fly
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy app
    # TODO put back ubuntu-latest once GitHub makes it work properly
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
