name: Test

on:
  workflow_call:

# Prevent concurrent runs on the same branch. In case of conflict,
# the oldest run will be cancelled.
concurrency:
  group: ${{ github.workflow }}-test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # Ensure everything is run in the test environment,
  # avoiding multiple compilations of the same code.
  MIX_ENV: test

jobs:
  build:
    name: Validate code
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Elixir
        id: elixir-install
        uses: ./.github/actions/setup-elixir
      - name: Build project
        uses: ./.github/actions/build-elixir
        with:
          otp-version: ${{ steps.elixir-install.outputs.otp-version }}
          elixir-version: ${{ steps.elixir-install.outputs.elixir-version }}
      - name: Setup Node
        uses: ./.github/actions/setup-node
      - name: Build assets
        uses: ./.github/actions/build-assets

      - name: Check dependencies
        uses: ./.github/actions/test-elixir-deps
      - name: Run code style checks
        uses: ./.github/actions/test-elixir-code
      - name: Check assets style
        uses: ./.github/actions/test-assets
      - name: Build PLT
        uses: ./.github/actions/build-plt
        with:
          otp-version: ${{ steps.elixir-install.outputs.otp-version }}
          elixir-version: ${{ steps.elixir-install.outputs.elixir-version }}
      - name: Run dialyzer
        uses: ./.github/actions/test-dialyzer

  test:
    name: Build and test
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: anacounts_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Elixir
        id: elixir-install
        uses: ./.github/actions/setup-elixir
      - name: Build project
        uses: ./.github/actions/build-elixir
        with:
          otp-version: ${{ steps.elixir-install.outputs.otp-version }}
          elixir-version: ${{ steps.elixir-install.outputs.elixir-version }}
      - name: Run unit tests
        uses: ./.github/actions/test-elixir-unit

  dockerfile:
    name: Validate Dockerfile
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build Dockerfile
        uses: ./.github/actions/test-dockerfile
