
# To use this workflow, you must have GitHub Advanced Security (GHAS) enabled for your repository.
# Once the workflow has run, review the "Security" tab of your repository.
name: Weekly Security Scan

on:
  schedule:
    - cron: '29 04 * * 6'

permissions:
  contents: read

jobs:
  security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run security scan
        uses: ./.github/workflows/composite/scan-code
